### ISSUE TITLE
Does not detect my Loupedeck CT

### ISSUE THREAD

**Issue by bruggenbill** [vurdalakov/loupedeckcttool#1]
Due to my setup I have my CT connected via a usb hub. It does not detect it. 
The loupedeck software detects it no problem and it works with all the apps I use it on (PM6+, LRC and PS) so I do not see why your tool cannot see it.
I hope you can fix this because I feel this tool would be really useful.

**Comment by vurdalakov** [comment]
This tool is not needed anymore if you update Loupedeck software to the latest version available and then update your Loupedeck CT and Loupedeck Live devices with the latest firmware.

This tool solves the "slow Internet" problem that was caused by the "Ethernet over USB" way the old Loupedeck software was communicating with CT/Live devices. In the recent software versions (4.3 or later) and firmware versions (0.2.5 or later) Loupedeck moved to "CDC over USB" way, and that eliminated the "slow Internet" problem.
